# Generated by Django 5.1 on 2024-08-15 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('minie_picture', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation_title', models.CharField(max_length=250)),
                ('navigation_headline', models.TextField()),
                ('navigation_content', models.TextField()),
                ('navigation_image', models.ImageField(upload_to='navigation/')),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_level', models.CharField(max_length=150)),
                ('painting_description', models.TextField()),
                ('painting_example', models.ImageField(upload_to='level/')),
                ('painting_splash', models.ImageField(upload_to='level/')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_studio.navigation')),
            ],
        ),
    ]
