# Generated by Django 5.1 on 2024-08-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_title', models.CharField(max_length=150)),
                ('terms_content', models.TextField()),
            ],
        ),
    ]
